sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "mkdir -p node_modules &"
  - "npm install phantomjs"
  - "npm install velocity-cli"
  - "export PHANTOMJS_BIN=./node_modules/phantomjs/bin/phantomjs"
  - "export JASMINE_BROWSER=PhantomJS"

script:
  - meteor add rocketchat:livechat rocketchat:hubot sanjo:jasmine velocity:console-reporter
  - ./node_modules/velocity-cli/bin/velocity test-packages --ci
  - ./node_modules/velocity-cli/bin/velocity test-app --ci
  - meteor build --server demo.rocket.chat ./
