sudo: required
language: node_js
branches:	
  only:
  - travis-001
node_js:
  - "0.10"

before_install:
  - "curl https://install.meteor.com | /bin/sh"

script:
  - mkdir ../build
  - meteor build ../build
