sudo: required
language: node_js
branches:
  only:
  - master
node_js:
- '0.10'
before_install:
- curl https://install.meteor.com | /bin/sh
- mkdir -p node_modules
- npm install phantomjs
- npm install velocity-cli
- export PHANTOMJS_BIN=./node_modules/phantomjs/bin/phantomjs
- export JASMINE_BROWSER=PhantomJS
- export DEBUG=1
- export JASMINE_DEBUG=1
- export VELOCITY_DEBUG=1
- export VELOCITY_DEBUG_MIRROR=1

script:
- meteor add sanjo:jasmine velocity:console-reporter
- meteor update
- ./node_modules/velocity-cli/bin/velocity test-packages --ci
- meteor --test --once