sudo: required
language: node_js
branches:
  only:
  - master
node_js:
- '0.10'
before_install:
- curl https://install.meteor.com | /bin/sh
- npm install -g npm@'>=2.13.5'
- mkdir -p node_modules
- npm install phantomjs
- npm install velocity-cli
- export PHANTOMJS_BIN=./node_modules/phantomjs/bin/phantomjs
- export JASMINE_BROWSER=PhantomJS
script:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then echo "Building PR $TRAVIS_PULL_REQUEST"; meteor build ../build; exit $?; fi
- cd .travis
- npm install
- npm start
- cd ..
- meteor build ../build
- cd .travis
- sh ./namefiles.sh
- cd ..
- meteor add rocketchat:livechat
- meteor add rocketchat:hubot
- meteor add sanjo:jasmine@0.20.2 velocity:console-reporter
- ./node_modules/velocity-cli/bin/velocity test-packages --ci
- ./node_modules/velocity-cli/bin/velocity test-app --ci
- meteor build --server demo.rocket.chat ./
- meteor build --server demo.rocket.chat  ../build
- cd .travis
- sh ./namedemo.sh
- cd ..
after_deploy:
- "curl -H \"Content-Type: application/json\" --data \"{'build': true}\" -X POST https://registry.hub.docker.com/u/singli/rocket.chat/trigger/$PUSHTOKEN/"
deploy:
  provider: s3
  access_key_id: "AKIAIKIA7H7D47KUHYCA"
  secret_access_key: $ACCESSKEY
  bucket: "rocketchatbuild"
  skip_cleanup: true
  local_dir: ../build
  on:
    branch: master
